//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialForum.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id_Order { get; set; }
        public Nullable<int> Id_Basket { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string IsConcluded { get; set; }
    
        public virtual Basket Basket { get; set; }
    }
}
